In [1]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp

# For Regression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

# Python script for confusion matrix creation. 
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics

In [2]:
dataset=pd.read_excel("1056_DES_709-50.xlsx",index_col=0)

In [3]:
dataset.shape

(1056, 51)

In [4]:
dataset

,ATS4v,ATS5v,ATS6v,ATS6e,ATS4p,ATS5p,ATS6i,ATSC0i,C3SP3,TIC3,...,GRAVH-1,GRAVH-2,GRAVH-3,GRAV-5,GRAV-6,MOMI-R,RDF40v,RDF45v,RDF40p,Act
Name,,,,,,,,,,,,,,,,,,,,,
1Co,74972.04913,91584.15521,104963.53270,3520.108192,649.839191,771.461184,71279.71493,164.306571,11,442.308369,...,6295.700561,79.345451,18.464945,130.395020,25.714258,9.233328,32.259864,46.220205,49.269901,85.3
2Co,78219.40383,96694.87583,112749.25830,3737.366172,673.448064,818.330329,75177.02490,172.592097,11,489.430640,...,6517.267707,80.729596,18.679067,133.093584,26.067822,9.329740,41.845360,56.428289,64.072547,98.7
3Co,82026.26592,101805.59650,120985.23870,3954.671584,705.059969,865.199474,79085.26869,180.771820,13,511.264120,...,6587.169530,81.161380,18.745612,136.255022,26.479006,9.375641,36.550937,52.951083,54.711126,77.3
4Co,76773.31216,93352.74620,106595.51600,3666.694212,664.214202,786.600199,75156.40094,168.463704,12,456.700914,...,6370.785121,79.817198,18.538062,131.337879,25.838066,9.400133,32.647603,46.292729,49.802305,76.0
5Co,80020.66685,98913.72165,115385.07610,3888.742208,687.823074,835.482193,78672.16965,176.694102,12,507.804752,...,6611.229254,81.309466,18.768407,134.091180,26.197920,9.464786,42.293299,56.818763,64.713770,89.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,104199.97100,129804.38270,156636.61070,5193.361960,886.825808,1094.501707,104136.95230,232.232426,17,714.695353,...,8208.396556,90.600202,20.172177,149.076087,28.115037,11.850319,44.364582,71.516077,68.212366,37.0
1053,55861.08930,63830.97184,66165.97433,2376.556604,510.078803,572.287347,48394.59655,127.490763,7,361.709099,...,4909.778604,70.069812,16.996284,109.827260,22.933663,8.154431,36.262089,38.272045,62.935514,102.0
1054,59108.44399,68941.69246,73951.69993,2593.814584,533.687676,619.156492,52291.90651,135.593581,7,397.963798,...,5048.751009,71.054564,17.155155,112.303189,23.277056,8.357372,37.260848,40.195730,64.729371,83.2
1055,62915.30609,74052.41308,82187.68036,2811.119996,565.299581,666.025637,56200.15030,143.582874,9,417.358544,...,5266.177558,72.568434,17.397967,115.470692,23.712709,8.401494,40.924067,45.648029,69.625644,70.1
1056,57662.35232,65599.56282,67797.95767,2523.142624,524.453813,587.426362,52271.28256,131.558022,8,378.729026,...,5001.110828,70.718532,17.101026,110.842553,23.074786,8.375663,36.764252,38.596359,63.639191,109.0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 1Co to 1056
Data columns (total 51 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ATS4v    1056 non-null   float64
 1   ATS5v    1056 non-null   float64
 2   ATS6v    1056 non-null   float64
 3   ATS6e    1056 non-null   float64
 4   ATS4p    1056 non-null   float64
 5   ATS5p    1056 non-null   float64
 6   ATS6i    1056 non-null   float64
 7   ATSC0i   1056 non-null   float64
 8   C3SP3    1056 non-null   int64
 9   TIC3     1056 non-null   float64
 10  TIC4     1056 non-null   float64
 11  TIC5     1056 non-null   float64
 12  CIC0     1056 non-null   float64
 13  CIC1     1056 non-null   float64
 14  CIC2     1056 non-null   float64
 15  MPC2     1056 non-null   int64
 16  MPC3     1056 non-null   int64
 17  piPC1    1056 non-null   float64
 18  piPC2    1056 non-null   float64
 19  piPC3    1056 non-null   float64
 20  piPC4    1056 non-null   float64
 21  piPC5    1056 non-null   float64
 22  GGI6     1056 non-null   float64
 23  GGI8     1056 non-null   float64
 24  GGI9     1056 non-null   float64
 25  VAdjMat  1056 non-null   float64
 26  MWC2     1056 non-null   float64
 27  MWC3     1056 non-null   float64
 28  MWC4     1056 non-null   float64
 29  MWC5     1056 non-null   float64
 30  MWC6     1056 non-null   float64
 31  MWC7     1056 non-null   float64
 32  TWC      1056 non-null   float64
 33  SRW2     1056 non-null   float64
 34  SRW4     1056 non-null   float64
 35  SRW6     1056 non-null   float64
 36  SRW8     1056 non-null   float64
 37  WPOL     1056 non-null   int64
 38  Zagreb   1056 non-null   int64
 39  GRAV-2   1056 non-null   float64
 40  GRAV-3   1056 non-null   float64
 41  GRAVH-1  1056 non-null   float64
 42  GRAVH-2  1056 non-null   float64
 43  GRAVH-3  1056 non-null   float64
 44  GRAV-5   1056 non-null   float64
 45  GRAV-6   1056 non-null   float64
 46  MOMI-R   1056 non-null   float64
 47  RDF40v   1056 non-null   float64
 48  RDF45v   1056 non-null   float64
 49  RDF40p   1056 non-null   float64
 50  Act      1056 non-null   float64
dtypes: float64(46), int64(5)
memory usage: 429.0+ KB

In [6]:
# to check the null values 
dataset.isnull().sum()

ATS4v      0
ATS5v      0
ATS6v      0
ATS6e      0
ATS4p      0
ATS5p      0
ATS6i      0
ATSC0i     0
C3SP3      0
TIC3       0
TIC4       0
TIC5       0
CIC0       0
CIC1       0
CIC2       0
MPC2       0
MPC3       0
piPC1      0
piPC2      0
piPC3      0
piPC4      0
piPC5      0
GGI6       0
GGI8       0
GGI9       0
VAdjMat    0
MWC2       0
MWC3       0
MWC4       0
MWC5       0
MWC6       0
MWC7       0
TWC        0
SRW2       0
SRW4       0
SRW6       0
SRW8       0
WPOL       0
Zagreb     0
GRAV-2     0
GRAV-3     0
GRAVH-1    0
GRAVH-2    0
GRAVH-3    0
GRAV-5     0
GRAV-6     0
MOMI-R     0
RDF40v     0
RDF45v     0
RDF40p     0
Act        0
dtype: int64

In [7]:
dataset.isnull().count()

ATS4v      1056
ATS5v      1056
ATS6v      1056
ATS6e      1056
ATS4p      1056
ATS5p      1056
ATS6i      1056
ATSC0i     1056
C3SP3      1056
TIC3       1056
TIC4       1056
TIC5       1056
CIC0       1056
CIC1       1056
CIC2       1056
MPC2       1056
MPC3       1056
piPC1      1056
piPC2      1056
piPC3      1056
piPC4      1056
piPC5      1056
GGI6       1056
GGI8       1056
GGI9       1056
VAdjMat    1056
MWC2       1056
MWC3       1056
MWC4       1056
MWC5       1056
MWC6       1056
MWC7       1056
TWC        1056
SRW2       1056
SRW4       1056
SRW6       1056
SRW8       1056
WPOL       1056
Zagreb     1056
GRAV-2     1056
GRAV-3     1056
GRAVH-1    1056
GRAVH-2    1056
GRAVH-3    1056
GRAV-5     1056
GRAV-6     1056
MOMI-R     1056
RDF40v     1056
RDF45v     1056
RDF40p     1056
Act        1056
dtype: int64

In [8]:
#independent and dependent features
x = dataset.iloc[:, 0:50].astype(float)

In [9]:
x

,ATS4v,ATS5v,ATS6v,ATS6e,ATS4p,ATS5p,ATS6i,ATSC0i,C3SP3,TIC3,...,GRAV-3,GRAVH-1,GRAVH-2,GRAVH-3,GRAV-5,GRAV-6,MOMI-R,RDF40v,RDF45v,RDF40p
Name,,,,,,,,,,,,,,,,,,,,,
1Co,74972.04913,91584.15521,104963.53270,3520.108192,649.839191,771.461184,71279.71493,164.306571,11.0,442.308369,...,17.875992,6295.700561,79.345451,18.464945,130.395020,25.714258,9.233328,32.259864,46.220205,49.269901
2Co,78219.40383,96694.87583,112749.25830,3737.366172,673.448064,818.330329,75177.02490,172.592097,11.0,489.430640,...,18.030809,6517.267707,80.729596,18.679067,133.093584,26.067822,9.329740,41.845360,56.428289,64.072547
3Co,82026.26592,101805.59650,120985.23870,3954.671584,705.059969,865.199474,79085.26869,180.771820,13.0,511.264120,...,18.120045,6587.169530,81.161380,18.745612,136.255022,26.479006,9.375641,36.550937,52.951083,54.711126
4Co,76773.31216,93352.74620,106595.51600,3666.694212,664.214202,786.600199,75156.40094,168.463704,12.0,456.700914,...,17.939106,6370.785121,79.817198,18.538062,131.337879,25.838066,9.400133,32.647603,46.292729,49.802305
5Co,80020.66685,98913.72165,115385.07610,3888.742208,687.823074,835.482193,78672.16965,176.694102,12.0,507.804752,...,18.096281,6611.229254,81.309466,18.768407,134.091180,26.197920,9.464786,42.293299,56.818763,64.713770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,104199.97100,129804.38270,156636.61070,5193.361960,886.825808,1094.501707,104136.95230,232.232426,17.0,714.695353,...,19.414426,8208.396556,90.600202,20.172177,149.076087,28.115037,11.850319,44.364582,71.516077,68.212366
1053,55861.08930,63830.97184,66165.97433,2376.556604,510.078803,572.287347,48394.59655,127.490763,7.0,361.709099,...,16.471709,4909.778604,70.069812,16.996284,109.827260,22.933663,8.154431,36.262089,38.272045,62.935514
1054,59108.44399,68941.69246,73951.69993,2593.814584,533.687676,619.156492,52291.90651,135.593581,7.0,397.963798,...,16.619993,5048.751009,71.054564,17.155155,112.303189,23.277056,8.357372,37.260848,40.195730,64.729371
1055,62915.30609,74052.41308,82187.68036,2811.119996,565.299581,666.025637,56200.15030,143.582874,9.0,417.358544,...,16.773735,5266.177558,72.568434,17.397967,115.470692,23.712709,8.401494,40.924067,45.648029,69.625644
1056,57662.35232,65599.56282,67797.95767,2523.142624,524.453813,587.426362,52271.28256,131.558022,8.0,378.729026,...,16.545923,5001.110828,70.718532,17.101026,110.842553,23.074786,8.375663,36.764252,38.596359,63.639191

In [10]:
y = dataset['Act']

In [11]:
y

Name
1Co      85.3
2Co      98.7
3Co      77.3
4Co      76.0
5Co      89.3
        ...
1052     37.0
1053    102.0
1054     83.2
1055     70.1
1056    109.0
Name: Act, Length: 1056, dtype: float64

In [12]:
x_model, x_extest, y_model, y_extest = train_test_split(x,y,test_size=.2, random_state = 7000, shuffle=True)

In [13]:
x_model.shape

(844, 50)

In [14]:
x_train, x_test2, y_train, y_test2 = train_test_split(x_model,y_model,test_size=.3, random_state = 7000, shuffle=True)

In [15]:
x_train.shape

(590, 50)

In [16]:
x_test2.shape

(254, 50)

In [17]:
x_val, x_test, y_val, y_test = train_test_split(x_test2,y_test2,test_size=.5, random_state = 7000, shuffle=True)

In [18]:
x_test.shape

(127, 50)

In [19]:
x_val.shape

(127, 50)

In [20]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
regressor = RandomForestRegressor ( n_estimators = 100,max_depth=None,min_weight_fraction_leaf=0.0,
                                   max_features='auto', min_impurity_decrease=0.2, ccp_alpha=0.0,max_leaf_nodes=None, 
                                   min_samples_split=2, min_samples_leaf=1, random_state = 1)

In [22]:
regressor.fit(x_train, y_train)

RandomForestRegressor(min_impurity_decrease=0.2, random_state=1)

In [23]:
# compute the testing accuracy
y_pred = regressor.predict(x_test)

In [24]:
y_pred_train = regressor.predict(x_train)

In [25]:
y_pred_val = regressor.predict(x_val)

In [26]:
y_pred_extest = regressor.predict(x_extest)

In [27]:
y_pred_model = regressor.predict(x_model)

In [28]:
y_pred_all = regressor.predict(x)

In [29]:
  print("\n")
  print("overall Performance: ", )

overall Performance:

In [30]:
 # model evaluation for testing set
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
r2 = metrics.r2_score(y_test, y_pred)

In [31]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 27.727426063764828
MSE is 1334.39657848071
R2 score is 0.5008345983726934

In [32]:
  # model evaluation for training set
maeTrain = metrics.mean_absolute_error(y_train, y_pred_train)
mseTrain = metrics.mean_squared_error(y_train, y_pred_train)
r2Train = metrics.r2_score(y_train, y_pred_train)

In [33]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain))
print('MSE is {}'.format(mseTrain))
print('R2 score is {}'.format(r2Train))

The model performance for training set
--------------------------------------
MAE is 9.498419553037404
MSE is 174.83632579305686
R2 score is 0.9255874007713343

In [34]:
cvscoreval = (cross_val_score(regressor,x_train,y_train.ravel(),cv=5).mean())

In [35]:
print("The CV score for Training set")
print("--------------------------------------")
print (-cross_val_score(regressor,x_val,y_val.ravel(),cv=5))
print('Q2 is {}'.format(cvscoreval))

The CV score for Training set
--------------------------------------
[ 0.28610476 -0.10690852 -0.24649149 -0.44002791 -0.20318014]
Q2 is 0.44993996437024925

In [36]:
## model evaluation for extest set
maeex = metrics.mean_absolute_error(y_extest, y_pred_extest)
mseex = metrics.mean_squared_error(y_extest, y_pred_extest)
r2ex = metrics.r2_score(y_extest, y_pred_extest)

In [37]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex))
print('MSE is {}'.format(mseex))
print('R2 score is {}'.format(r2ex))

The model performance for extest set
--------------------------------------
MAE is 25.126178514118685
MSE is 1365.926447141394
R2 score is 0.4480912811861054

In [38]:
## model evaluation for val set
maevl = metrics.mean_absolute_error(y_val, y_pred_val)
msevl = metrics.mean_squared_error(y_val, y_pred_val)
r2vl = metrics.r2_score(y_val, y_pred_val)

In [39]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl))
print('MSE is {}'.format(msevl))
print('R2 score is {}'.format(r2vl))

The model performance for val set
--------------------------------------
MAE is 25.769943895886104
MSE is 1169.261903934465
R2 score is 0.3728834230578725

In [40]:
## model evaluation for modeling set
maeM = metrics.mean_absolute_error(y_model, y_pred_model)
mseM = metrics.mean_squared_error(y_model, y_pred_model)
r2eM = metrics.r2_score(y_model, y_pred_model)

In [41]:
print("The model performance for Modeling set")
print("--------------------------------------")
print('MAE is {}'.format(maeM))
print('MSE is {}'.format(mseM))
print('R2 score is {}'.format(r2eM))

The model performance for Modeling set
--------------------------------------
MAE is 14.68985014356367
MSE is 498.9550467827379
R2 score is 0.7857167516176224

In [42]:
#CV od Modeling set 
cvscoremodel = (cross_val_score(regressor,x_model,y_model.ravel(),cv=5).mean())

In [43]:
print("The CV score for modelingset")
print("--------------------------------------")
print (cross_val_score(regressor,x_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremodel))

The CV score for modelingset
--------------------------------------
[0.50679419 0.44599674 0.41431793 0.53834954 0.58563342]
Q2 is 0.4982183648097104

In [44]:
#Performance on Out-bag sample 
# R2 value on unseen data (cross validation using hold-out set concept)
random_forest_out_of_bag = RandomForestRegressor(oob_score=True,n_estimators = 100, random_state = 1)

In [45]:
random_forest_out_of_bag.fit(x_train, y_train)

RandomForestRegressor(oob_score=True, random_state=1)

In [46]:
print(random_forest_out_of_bag.oob_score_)

0.4642325545396192

In [47]:
#Randomize search CV
from sklearn.model_selection import RandomizedSearchCV

In [48]:
#number of trees in the random forest 
n_estimators = [100,200,300]
criterion = ['mae', 'mse']
#number of features to cinsider in at every split 
max_features = ['auto', 'sqrt', 'log2']
#Max number of levels in tree
max_depth = [1,2,3]
#Minimum number ofsamples required to split a node 
min_samples_split =[int(x) for x in np.linspace(start = 2, stop = 10, num = 3)]
#Minimum number ofsamples required at each leaf node
min_samples_leaf =[1,2]
#mathod of selceting samples of training each tree 
bootstrap = [True, False]

In [49]:
# creatting parameter gride
param_grid_regressor= {'n_estimators': n_estimators,
                       'criterion': criterion,
                       'max_features': max_features,
                       'max_depth': max_depth,
                       'min_samples_split': min_samples_split,
                      'min_samples_leaf':min_samples_leaf,
                       'bootstrap':bootstrap }

In [50]:
regressor1 = RandomForestRegressor ()

In [51]:
regressor1_random = RandomizedSearchCV(estimator = regressor1, param_distributions=param_grid_regressor, n_iter = 100,
                              cv = 5, verbose =2,
                              n_jobs= -1, scoring = 'neg_mean_squared_error' )

In [52]:
regressor1_random.fit(x_model, y_model)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['mae', 'mse'],
                                        'max_depth': [1, 2, 3],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 6, 10],
                                        'n_estimators': [100, 200, 300]},
                   scoring='neg_mean_squared_error', verbose=2)

In [53]:
regressor1_random.best_params_

{'n_estimators': 100,
 'min_samples_split': 6,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 3,
 'criterion': 'mse',
 'bootstrap': True}

In [54]:
regressor1_random.best_score_

-1430.5167747554583

In [55]:
# parameter tuning grid searchCV
from sklearn.model_selection import GridSearchCV

In [56]:
RandomForestRegressor?

In [ ]:
#number of trees in the random forest 
n_estimators = [100,200,300]
criterion = ['mae', 'mse']
#number of features to cinsider in at every split 
max_features = ['auto', 'sqrt', 'log2']
#Max number of levels in tree
max_depth = [1,2,3]
#Minimum number ofsamples required to split a node 
min_samples_split =[int(x) for x in np.linspace(start = 2, stop = 10, num = 3)]
#Minimum number ofsamples required at each leaf node
min_samples_leaf =[1,2]
#mathod of selceting samples of training each tree 
bootstrap = [True, False]

In [57]:
# creatting parameter gride
param_grid_regressor= {'n_estimators': n_estimators,
                       'criterion': criterion,
                       'max_features': max_features,
                       'max_depth': max_depth,
                       'min_samples_split': min_samples_split,
                      'min_samples_leaf':min_samples_leaf,
                       'bootstrap':bootstrap }

In [58]:
print (param_grid_regressor)

{'n_estimators': [100, 200, 300], 'criterion': ['mae', 'mse'], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [1, 2, 3], 'min_samples_split': [2, 6, 10], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}

In [59]:
regressor1 = RandomForestRegressor ()

In [60]:
regressor1_grid = GridSearchCV( estimator = regressor1, param_grid = param_grid_regressor,
                              cv = 5, verbose = 2, n_jobs= -1, scoring = "neg_mean_squared_error")

In [61]:
regressor1_grid.fit(x_train, y_train)

Fitting 5 folds for each of 648 candidates, totalling 3240 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['mae', 'mse'], 'max_depth': [1, 2, 3],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 6, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='neg_mean_squared_error', verbose=2)

In [62]:
regressor1_grid.best_params_

{'bootstrap': True,
 'criterion': 'mse',
 'max_depth': 3,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 10,
 'n_estimators': 100}

In [63]:
regressor1_grid.best_score_

-1497.1844415337066

In [64]:
#manual seach engine 
regressor2 =  RandomForestRegressor (bootstrap = "True", criterion = "mse", max_depth = 3, max_features = "auto",
                              min_samples_leaf = 1, min_samples_split = 10,n_estimators = 100, random_state = 1)

In [65]:
regressor2.fit (x_train, y_train)

RandomForestRegressor(bootstrap='True', max_depth=3, min_samples_split=10,
                      random_state=1)

In [66]:
y_pred1 = regressor2.predict(x_test)

In [67]:
y_pred_train1 = regressor2.predict(x_train)

In [68]:
y_pred_extest1 = regressor2.predict(x_extest)

In [69]:
y_pred_model1 = regressor2.predict(x_model)

In [70]:
mae2 = metrics.mean_absolute_error(y_test, y_pred1)
mse2 = metrics.mean_squared_error(y_test, y_pred1)
r22 = metrics.r2_score(y_test, y_pred1)

In [71]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae2))
print('MSE is {}'.format(mse2))
print('R2 score is {}'.format(r22))

The model performance for testing set
--------------------------------------
MAE is 31.339186736108832
MSE is 1639.5365080377392
R2 score is 0.3866891502006946

In [72]:
maeTrain2 = metrics.mean_absolute_error(y_train, y_pred_train1)
mseTrain2 = metrics.mean_squared_error(y_train, y_pred_train1)
r2Train2 = metrics.r2_score(y_train, y_pred_train1)

In [73]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain2))
print('MSE is {}'.format(mseTrain2))
print('R2 score is {}'.format(r2Train2))

The model performance for training set
--------------------------------------
MAE is 25.326287095837213
MSE is 1157.6574675326262
R2 score is 0.5072860243154432

In [74]:
maeExtest2 = metrics.mean_absolute_error(y_model, y_pred_model1)
mseExtest2 = metrics.mean_squared_error(y_model, y_pred_model1)
r2Extest2 = metrics.r2_score(y_model, y_pred_model1)

In [75]:
print("The model performance for modeling set")
print("--------------------------------------")
print('MAE is {}'.format(maeExtest2))
print('MSE is {}'.format(mseExtest2))
print('R2 score is {}'.format(r2Extest2))

The model performance for modeling set
--------------------------------------
MAE is 26.492733546933003
MSE is 1238.5232408826041
R2 score is 0.4680988097732255

In [76]:
cvscoreval = (-cross_val_score(regressor2,x_val,y_val.ravel(),cv=5).mean())
MAE = (-cross_val_score(regressor2,x_val,y_val.ravel(),cv=5, scoring = "neg_mean_absolute_error").mean())
MSE = (-cross_val_score(regressor2,x_val,y_val.ravel(),cv=5, scoring = "neg_mean_squared_error").mean())

In [77]:
print("The CV score for whole dataset")
print("--------------------------------------")
print('Q2 is {}'.format(cvscoreval))
print('MAE is {}'.format(MAE))
print('MSE is {}'.format(MSE))

The CV score for whole dataset
--------------------------------------
Q2 is -0.13669222659184144
MAE is 30.261805890920137
MSE is 1478.933780251314

In [78]:
random_forest_out_of_bag1 = RandomForestRegressor(oob_score=True,bootstrap = "True", criterion = "mse", max_depth = 2, max_features = "auto",
                              min_samples_leaf = 1, min_samples_split = 2,n_estimators = 300, random_state = 1)

In [79]:
random_forest_out_of_bag1.fit(x_train, y_train)

RandomForestRegressor(bootstrap='True', max_depth=2, n_estimators=300,
                      oob_score=True, random_state=1)

In [80]:
print(random_forest_out_of_bag1.oob_score_)

0.32390269006925876